/*
 * Copyright (c) 2016-2022 VMware, Inc. All Rights Reserved.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */

const ONE_DAY = 24 * 3600 * 1000;

export const elements: {
  name: string;
  symbol: string;
  number: number;
  electronegativity: number;
  lastModified: Date;
}[] = [
  {
    name: 'Actinium',
    symbol: 'Ac',
    number: 89,
    electronegativity: 1.1,
    lastModified: new Date(Date.now() - 89 * ONE_DAY),
  },
  {
    name: 'Aluminum',
    symbol: 'Al',
    number: 13,
    electronegativity: 1.61,
    lastModified: new Date(Date.now() - 13 * ONE_DAY),
  },
  {
    name: 'Americium',
    symbol: 'Am',
    number: 95,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 95 * ONE_DAY),
  },
  {
    name: 'Antimony',
    symbol: 'Sb',
    number: 51,
    electronegativity: 2.05,
    lastModified: new Date(Date.now() - 51 * ONE_DAY),
  },
  { name: 'Argon', symbol: 'Ar', number: 18, electronegativity: 0, lastModified: new Date(Date.now() - 18 * ONE_DAY) },
  {
    name: 'Arsenic',
    symbol: 'As',
    number: 33,
    electronegativity: 2.18,
    lastModified: new Date(Date.now() - 33 * ONE_DAY),
  },
  {
    name: 'Astatine',
    symbol: 'At',
    number: 85,
    electronegativity: 2.2,
    lastModified: new Date(Date.now() - 85 * ONE_DAY),
  },
  {
    name: 'Barium',
    symbol: 'Ba',
    number: 56,
    electronegativity: 0.89,
    lastModified: new Date(Date.now() - 56 * ONE_DAY),
  },
  {
    name: 'Berkelium',
    symbol: 'Bk',
    number: 97,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 97 * ONE_DAY),
  },
  {
    name: 'Beryllium',
    symbol: 'Be',
    number: 4,
    electronegativity: 1.57,
    lastModified: new Date(Date.now() - 4 * ONE_DAY),
  },
  {
    name: 'Bismuth',
    symbol: 'Bi',
    number: 83,
    electronegativity: 2.02,
    lastModified: new Date(Date.now() - 83 * ONE_DAY),
  },
  {
    name: 'Bohrium',
    symbol: 'Bh',
    number: 107,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 107 * ONE_DAY),
  },
  { name: 'Boron', symbol: 'B', number: 5, electronegativity: 2.04, lastModified: new Date(Date.now() - 5 * ONE_DAY) },
  {
    name: 'Bromine',
    symbol: 'Br',
    number: 35,
    electronegativity: 2.96,
    lastModified: new Date(Date.now() - 35 * ONE_DAY),
  },
  {
    name: 'Cadmium',
    symbol: 'Cd',
    number: 48,
    electronegativity: 1.69,
    lastModified: new Date(Date.now() - 48 * ONE_DAY),
  },
  {
    name: 'Calcium',
    symbol: 'Ca',
    number: 20,
    electronegativity: 1,
    lastModified: new Date(Date.now() - 20 * ONE_DAY),
  },
  {
    name: 'Californium',
    symbol: 'Cf',
    number: 98,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 98 * ONE_DAY),
  },
  { name: 'Carbon', symbol: 'C', number: 6, electronegativity: 2.55, lastModified: new Date(Date.now() - 6 * ONE_DAY) },
  {
    name: 'Cerium',
    symbol: 'Ce',
    number: 58,
    electronegativity: 1.12,
    lastModified: new Date(Date.now() - 58 * ONE_DAY),
  },
  {
    name: 'Cesium',
    symbol: 'Cs',
    number: 55,
    electronegativity: 0.79,
    lastModified: new Date(Date.now() - 55 * ONE_DAY),
  },
  {
    name: 'Chlorine',
    symbol: 'Cl',
    number: 17,
    electronegativity: 3.16,
    lastModified: new Date(Date.now() - 17 * ONE_DAY),
  },
  {
    name: 'Chromium',
    symbol: 'Cr',
    number: 24,
    electronegativity: 1.66,
    lastModified: new Date(Date.now() - 24 * ONE_DAY),
  },
  {
    name: 'Cobalt',
    symbol: 'Co',
    number: 27,
    electronegativity: 1.88,
    lastModified: new Date(Date.now() - 27 * ONE_DAY),
  },
  {
    name: 'Copper',
    symbol: 'Cu',
    number: 29,
    electronegativity: 1.9,
    lastModified: new Date(Date.now() - 29 * ONE_DAY),
  },
  {
    name: 'Curium',
    symbol: 'Cm',
    number: 96,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 96 * ONE_DAY),
  },
  {
    name: 'Darmstadtium',
    symbol: 'Ds',
    number: 110,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 110 * ONE_DAY),
  },
  {
    name: 'Dubnium',
    symbol: 'Db',
    number: 105,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 105 * ONE_DAY),
  },
  {
    name: 'Dysprosium',
    symbol: 'Dy',
    number: 66,
    electronegativity: 1.22,
    lastModified: new Date(Date.now() - 66 * ONE_DAY),
  },
  {
    name: 'Einsteinium',
    symbol: 'Es',
    number: 99,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 99 * ONE_DAY),
  },
  {
    name: 'Erbium',
    symbol: 'Er',
    number: 68,
    electronegativity: 1.24,
    lastModified: new Date(Date.now() - 68 * ONE_DAY),
  },
  {
    name: 'Europium',
    symbol: 'Eu',
    number: 63,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 63 * ONE_DAY),
  },
  {
    name: 'Fermium',
    symbol: 'Fm',
    number: 100,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 100 * ONE_DAY),
  },
  {
    name: 'Fluorine',
    symbol: 'F',
    number: 9,
    electronegativity: 3.98,
    lastModified: new Date(Date.now() - 9 * ONE_DAY),
  },
  {
    name: 'Francium',
    symbol: 'Fr',
    number: 87,
    electronegativity: 0.7,
    lastModified: new Date(Date.now() - 87 * ONE_DAY),
  },
  {
    name: 'Gadolinium',
    symbol: 'Gd',
    number: 64,
    electronegativity: 1.2,
    lastModified: new Date(Date.now() - 64 * ONE_DAY),
  },
  {
    name: 'Gallium',
    symbol: 'Ga',
    number: 31,
    electronegativity: 1.81,
    lastModified: new Date(Date.now() - 31 * ONE_DAY),
  },
  {
    name: 'Germanium',
    symbol: 'Ge',
    number: 32,
    electronegativity: 2.01,
    lastModified: new Date(Date.now() - 32 * ONE_DAY),
  },
  {
    name: 'Gold',
    symbol: 'Au',
    number: 79,
    electronegativity: 2.54,
    lastModified: new Date(Date.now() - 79 * ONE_DAY),
  },
  {
    name: 'Hafnium',
    symbol: 'Hf',
    number: 72,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 72 * ONE_DAY),
  },
  {
    name: 'Hassium',
    symbol: 'Hs',
    number: 108,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 108 * ONE_DAY),
  },
  { name: 'Helium', symbol: 'He', number: 2, electronegativity: 0, lastModified: new Date(Date.now() - 2 * ONE_DAY) },
  {
    name: 'Holmium',
    symbol: 'Ho',
    number: 67,
    electronegativity: 1.23,
    lastModified: new Date(Date.now() - 67 * ONE_DAY),
  },
  {
    name: 'Hydrogen',
    symbol: 'H',
    number: 1,
    electronegativity: 2.2,
    lastModified: new Date(Date.now() - 1 * ONE_DAY),
  },
  {
    name: 'Indium',
    symbol: 'In',
    number: 49,
    electronegativity: 1.78,
    lastModified: new Date(Date.now() - 49 * ONE_DAY),
  },
  {
    name: 'Iodine',
    symbol: 'I',
    number: 53,
    electronegativity: 2.66,
    lastModified: new Date(Date.now() - 53 * ONE_DAY),
  },
  {
    name: 'Iridium',
    symbol: 'Ir',
    number: 77,
    electronegativity: 2.2,
    lastModified: new Date(Date.now() - 77 * ONE_DAY),
  },
  {
    name: 'Iron',
    symbol: 'Fe',
    number: 26,
    electronegativity: 1.83,
    lastModified: new Date(Date.now() - 26 * ONE_DAY),
  },
  {
    name: 'Krypton',
    symbol: 'Kr',
    number: 36,
    electronegativity: 3,
    lastModified: new Date(Date.now() - 36 * ONE_DAY),
  },
  {
    name: 'Lanthanum',
    symbol: 'La',
    number: 57,
    electronegativity: 1.1,
    lastModified: new Date(Date.now() - 57 * ONE_DAY),
  },
  {
    name: 'Lawrencium',
    symbol: 'Lr',
    number: 103,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 103 * ONE_DAY),
  },
  {
    name: 'Lead',
    symbol: 'Pb',
    number: 82,
    electronegativity: 2.33,
    lastModified: new Date(Date.now() - 82 * ONE_DAY),
  },
  {
    name: 'Lithium',
    symbol: 'Li',
    number: 3,
    electronegativity: 0.98,
    lastModified: new Date(Date.now() - 3 * ONE_DAY),
  },
  {
    name: 'Lutetium',
    symbol: 'Lu',
    number: 71,
    electronegativity: 1.27,
    lastModified: new Date(Date.now() - 71 * ONE_DAY),
  },
  {
    name: 'Magnesium',
    symbol: 'Mg',
    number: 12,
    electronegativity: 1.31,
    lastModified: new Date(Date.now() - 12 * ONE_DAY),
  },
  {
    name: 'Manganese',
    symbol: 'Mn',
    number: 25,
    electronegativity: 1.55,
    lastModified: new Date(Date.now() - 25 * ONE_DAY),
  },
  {
    name: 'Meitnerium',
    symbol: 'Mt',
    number: 109,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 109 * ONE_DAY),
  },
  {
    name: 'Mendelevium',
    symbol: 'Md',
    number: 101,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 101 * ONE_DAY),
  },
  {
    name: 'Mercury',
    symbol: 'Hg',
    number: 80,
    electronegativity: 2,
    lastModified: new Date(Date.now() - 80 * ONE_DAY),
  },
  {
    name: 'Molybdenum',
    symbol: 'Mo',
    number: 42,
    electronegativity: 2.16,
    lastModified: new Date(Date.now() - 42 * ONE_DAY),
  },
  {
    name: 'Neodymium',
    symbol: 'Nd',
    number: 60,
    electronegativity: 1.14,
    lastModified: new Date(Date.now() - 60 * ONE_DAY),
  },
  { name: 'Neon', symbol: 'Ne', number: 10, electronegativity: 0, lastModified: new Date(Date.now() - 10 * ONE_DAY) },
  {
    name: 'Neptunium',
    symbol: 'Np',
    number: 93,
    electronegativity: 1.36,
    lastModified: new Date(Date.now() - 93 * ONE_DAY),
  },
  {
    name: 'Nickel',
    symbol: 'Ni',
    number: 28,
    electronegativity: 1.91,
    lastModified: new Date(Date.now() - 28 * ONE_DAY),
  },
  {
    name: 'Niobium',
    symbol: 'Nb',
    number: 41,
    electronegativity: 1.6,
    lastModified: new Date(Date.now() - 41 * ONE_DAY),
  },
  {
    name: 'Nitrogen',
    symbol: 'N',
    number: 7,
    electronegativity: 3.04,
    lastModified: new Date(Date.now() - 7 * ONE_DAY),
  },
  {
    name: 'Nobelium',
    symbol: 'No',
    number: 102,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 102 * ONE_DAY),
  },
  {
    name: 'Oganesson',
    symbol: 'Uuo',
    number: 118,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 118 * ONE_DAY),
  },
  {
    name: 'Osmium',
    symbol: 'Os',
    number: 76,
    electronegativity: 2.2,
    lastModified: new Date(Date.now() - 76 * ONE_DAY),
  },
  { name: 'Oxygen', symbol: 'O', number: 8, electronegativity: 3.44, lastModified: new Date(Date.now() - 8 * ONE_DAY) },
  {
    name: 'Palladium',
    symbol: 'Pd',
    number: 46,
    electronegativity: 2.2,
    lastModified: new Date(Date.now() - 46 * ONE_DAY),
  },
  {
    name: 'Phosphorus',
    symbol: 'P',
    number: 15,
    electronegativity: 2.19,
    lastModified: new Date(Date.now() - 15 * ONE_DAY),
  },
  {
    name: 'Platinum',
    symbol: 'Pt',
    number: 78,
    electronegativity: 2.28,
    lastModified: new Date(Date.now() - 78 * ONE_DAY),
  },
  {
    name: 'Plutonium',
    symbol: 'Pu',
    number: 94,
    electronegativity: 1.28,
    lastModified: new Date(Date.now() - 94 * ONE_DAY),
  },
  {
    name: 'Polonium',
    symbol: 'Po',
    number: 84,
    electronegativity: 2,
    lastModified: new Date(Date.now() - 84 * ONE_DAY),
  },
  {
    name: 'Potassium',
    symbol: 'K',
    number: 19,
    electronegativity: 0.82,
    lastModified: new Date(Date.now() - 19 * ONE_DAY),
  },
  {
    name: 'Praseodymium',
    symbol: 'Pr',
    number: 59,
    electronegativity: 1.13,
    lastModified: new Date(Date.now() - 59 * ONE_DAY),
  },
  {
    name: 'Promethium',
    symbol: 'Pm',
    number: 61,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 61 * ONE_DAY),
  },
  {
    name: 'Protactinium',
    symbol: 'Pa',
    number: 91,
    electronegativity: 1.5,
    lastModified: new Date(Date.now() - 91 * ONE_DAY),
  },
  {
    name: 'Radium',
    symbol: 'Ra',
    number: 88,
    electronegativity: 0.9,
    lastModified: new Date(Date.now() - 88 * ONE_DAY),
  },
  { name: 'Radon', symbol: 'Rn', number: 86, electronegativity: 0, lastModified: new Date(Date.now() - 86 * ONE_DAY) },
  {
    name: 'Rhenium',
    symbol: 'Re',
    number: 75,
    electronegativity: 1.9,
    lastModified: new Date(Date.now() - 75 * ONE_DAY),
  },
  {
    name: 'Rhodium',
    symbol: 'Rh',
    number: 45,
    electronegativity: 2.28,
    lastModified: new Date(Date.now() - 45 * ONE_DAY),
  },
  {
    name: 'Roentgenium',
    symbol: 'Rg',
    number: 111,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 111 * ONE_DAY),
  },
  {
    name: 'Rubidium',
    symbol: 'Rb',
    number: 37,
    electronegativity: 0.82,
    lastModified: new Date(Date.now() - 37 * ONE_DAY),
  },
  {
    name: 'Ruthenium',
    symbol: 'Ru',
    number: 44,
    electronegativity: 2.2,
    lastModified: new Date(Date.now() - 44 * ONE_DAY),
  },
  {
    name: 'Rutherfordium',
    symbol: 'Rf',
    number: 104,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 104 * ONE_DAY),
  },
  {
    name: 'Samarium',
    symbol: 'Sm',
    number: 62,
    electronegativity: 1.17,
    lastModified: new Date(Date.now() - 62 * ONE_DAY),
  },
  {
    name: 'Scandium',
    symbol: 'Sc',
    number: 21,
    electronegativity: 1.36,
    lastModified: new Date(Date.now() - 21 * ONE_DAY),
  },
  {
    name: 'Seaborgium',
    symbol: 'Sg',
    number: 106,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 106 * ONE_DAY),
  },
  {
    name: 'Selenium',
    symbol: 'Se',
    number: 34,
    electronegativity: 2.55,
    lastModified: new Date(Date.now() - 34 * ONE_DAY),
  },
  {
    name: 'Silicon',
    symbol: 'Si',
    number: 14,
    electronegativity: 1.9,
    lastModified: new Date(Date.now() - 14 * ONE_DAY),
  },
  {
    name: 'Silver',
    symbol: 'Ag',
    number: 47,
    electronegativity: 1.93,
    lastModified: new Date(Date.now() - 47 * ONE_DAY),
  },
  {
    name: 'Sodium',
    symbol: 'Na',
    number: 11,
    electronegativity: 0.93,
    lastModified: new Date(Date.now() - 11 * ONE_DAY),
  },
  {
    name: 'Strontium',
    symbol: 'Sr',
    number: 38,
    electronegativity: 0.95,
    lastModified: new Date(Date.now() - 38 * ONE_DAY),
  },
  {
    name: 'Sulfur',
    symbol: 'S',
    number: 16,
    electronegativity: 2.58,
    lastModified: new Date(Date.now() - 16 * ONE_DAY),
  },
  {
    name: 'Tantalum',
    symbol: 'Ta',
    number: 73,
    electronegativity: 1.5,
    lastModified: new Date(Date.now() - 73 * ONE_DAY),
  },
  {
    name: 'Technetium',
    symbol: 'Tc',
    number: 43,
    electronegativity: 1.9,
    lastModified: new Date(Date.now() - 43 * ONE_DAY),
  },
  {
    name: 'Tellurium',
    symbol: 'Te',
    number: 52,
    electronegativity: 2.1,
    lastModified: new Date(Date.now() - 52 * ONE_DAY),
  },
  {
    name: 'Terbium',
    symbol: 'Tb',
    number: 65,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 65 * ONE_DAY),
  },
  {
    name: 'Thallium',
    symbol: 'Tl',
    number: 81,
    electronegativity: 1.62,
    lastModified: new Date(Date.now() - 81 * ONE_DAY),
  },
  {
    name: 'Thorium',
    symbol: 'Th',
    number: 90,
    electronegativity: 1.3,
    lastModified: new Date(Date.now() - 90 * ONE_DAY),
  },
  {
    name: 'Thulium',
    symbol: 'Tm',
    number: 69,
    electronegativity: 1.25,
    lastModified: new Date(Date.now() - 69 * ONE_DAY),
  },
  { name: 'Tin', symbol: 'Sn', number: 50, electronegativity: 1.96, lastModified: new Date(Date.now() - 50 * ONE_DAY) },
  {
    name: 'Titanium',
    symbol: 'Ti',
    number: 22,
    electronegativity: 1.54,
    lastModified: new Date(Date.now() - 22 * ONE_DAY),
  },
  {
    name: 'Tungsten',
    symbol: 'W',
    number: 74,
    electronegativity: 2.36,
    lastModified: new Date(Date.now() - 74 * ONE_DAY),
  },
  {
    name: 'Ununbium',
    symbol: 'Uub',
    number: 112,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 112 * ONE_DAY),
  },
  {
    name: 'Ununhexium',
    symbol: 'Uuh',
    number: 116,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 116 * ONE_DAY),
  },
  {
    name: 'Ununpentium',
    symbol: 'Uup',
    number: 115,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 115 * ONE_DAY),
  },
  {
    name: 'Ununquadium',
    symbol: 'Uuq',
    number: 114,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 114 * ONE_DAY),
  },
  {
    name: 'Ununseptium',
    symbol: 'Uus',
    number: 117,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 117 * ONE_DAY),
  },
  {
    name: 'Ununtrium',
    symbol: 'Uut',
    number: 113,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 113 * ONE_DAY),
  },
  {
    name: 'Uranium',
    symbol: 'U',
    number: 92,
    electronegativity: 1.38,
    lastModified: new Date(Date.now() - 92 * ONE_DAY),
  },
  {
    name: 'Vanadium',
    symbol: 'V',
    number: 23,
    electronegativity: 1.63,
    lastModified: new Date(Date.now() - 23 * ONE_DAY),
  },
  {
    name: 'Xenon',
    symbol: 'Xe',
    number: 54,
    electronegativity: 2.6,
    lastModified: new Date(Date.now() - 54 * ONE_DAY),
  },
  {
    name: 'Ytterbium',
    symbol: 'Yb',
    number: 70,
    electronegativity: 0,
    lastModified: new Date(Date.now() - 70 * ONE_DAY),
  },
  {
    name: 'Yttrium',
    symbol: 'Y',
    number: 39,
    electronegativity: 1.22,
    lastModified: new Date(Date.now() - 39 * ONE_DAY),
  },
  {
    name: 'Zinc',
    symbol: 'Zn',
    number: 30,
    electronegativity: 1.65,
    lastModified: new Date(Date.now() - 30 * ONE_DAY),
  },
  {
    name: 'Zirconium',
    symbol: 'Zr',
    number: 40,
    electronegativity: 1.33,
    lastModified: new Date(Date.now() - 40 * ONE_DAY),
  },
];
